### ISSUE TITLE
Background health check results should be used by `/health` endpoint

### ISSUE THREAD

**Issue by jkinkead** [Nordstrom/xrpc#116]
The background health check results [are silently discarded](https://github.com/Nordstrom/xrpc/blob/fe49c429ed8768d12faf59bdae8ea534ad844cd8/xrpc/src/main/java/com/nordstrom/xrpc/server/Router.java#L134), which isn't very helpful.

These should be stored in a place that can be used by the `/health` handler.

**Comment by jkinkead** [comment]
The [health check intervals](https://github.com/Nordstrom/xrpc/blob/fe49c429ed8768d12faf59bdae8ea534ad844cd8/xrpc/src/main/java/com/nordstrom/xrpc/server/Router.java#L123) should also be made configurable if these results are being used by the `/health` path.

**Comment by jkinkead** [comment]
If we use the builtin [`@Async`](http://metrics.dropwizard.io/4.0.0/apidocs/com/codahale/metrics/health/annotation/Async.html) annotation for all health checks, this Just Works.

I think we may want to retire the notion of running these in the background on our own.

**Comment by andyday** [comment]
not sure how I closed that...  reopened...

**Comment by andyday** [comment]
this was resolved by #144

**Comment by jkinkead** [comment]
#144 removed the background health checks entirely in favor of using @Async, per comments on this issue.
