### ISSUE TITLE
ClosedChannelException: null

### ISSUE THREAD

**Issue by andyday** [Nordstrom/xrpc#135]
At the end of each regression run we get the following ClosedChannelExceptions

```
WARN  i.n.h.s.ApplicationProtocolNegotiationHandler - [id: 0xcc3bed86, L:/127.0.0.1:8080 ! R:/127.0.0.1:60643] TLS handshake failed:
java.nio.channels.ClosedChannelException: null
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
```

this should be handled more gracefully

**Comment by jkinkead** [comment]
I believe this is `wrk` ungracefully terminating its last few connections.

You'll note that the number of exceptions printed exactly equals the number of worker threads `wrk` is invoked with.

**Comment by xjdr** [comment]
That is my assumption as well

**Comment by andyday** [comment]
closing based on this assumption...
