### ISSUE TITLE
return FullHttpResponse

### ISSUE THREAD

**Issue by skaoth** [Nordstrom/xrpc#24]
https://github.com/Nordstrom/xrpc/blob/0d0e002f0574dfb1e307db9dc7831344131195c7/src/main/java/com/nordstrom/xrpc/server/http/Recipes.java#L96

I think the newResponse method in Recipes.java should return 
a FullHttpResponse object and not a DefaultFullHttpResponse.
Http2Handler typecasts event handler responses to FullHttpResponse leading to an exception

**Comment by xjdr** [comment]
FIxed by 02c83bfabf08533d9e57a7571ace3e1d8393589c
