### ISSUE TITLE
Router should match on path ONLY, not full URI

### ISSUE THREAD

**Issue by jkinkead** [Nordstrom/xrpc#27]
[This line](https://github.com/Nordstrom/xrpc/blob/83a24cb6739d5273a7b99923fc0aa05e4809a513/src/main/java/com/nordstrom/xrpc/server/UrlRouter.java#L39) should be matching on the path ONLY. This matches query parameters, since it hits the whole URI.

**Comment by shine17** [comment]
I thinks this needs to be handled for both http 1.1 and http2 handlers

**Comment by jkinkead** [comment]
Patching `UrlRouter` should fix behavior in both HTTP/1.x & HTTP/2.

**Comment by xjdr** [comment]
solved by 1eb5226ef5a3c4bb8b34462353b51f02bca8cb98
