### ISSUE TITLE
Should have a way of getting query parameters easily

### ISSUE THREAD

**Issue by shine17** [Nordstrom/xrpc#29]
we have the use case of extracting the query string parameters in the request
we are trying get that from the getter   `@Getter private final FullHttpRequest h1Request`  in `XrpcRequest.java`
But this is returning null. 

We need someway of passing the query params as a hash map to the service handlers.

**Comment by jkinkead** [comment]
This is definitely something we talked about, but never implemented.

**Comment by xjdr** [comment]
solved by 1eb5226ef5a3c4bb8b34462353b51f02bca8cb98
