### ISSUE TITLE
unable to get request body from h1Request getter property

### ISSUE THREAD

**Issue by shine17** [Nordstrom/xrpc#30]
we have the use case of extracting the request body for our post/put methods.
we are trying get that from the getter `@Getter private final FullHttpRequest h1Request `in `XrpcRequest.java` . We are thinking to use `getH1Request().content()`.
But the `getH1Request` is returning null.

We need someway of passing the request body to the service handlers as a byte buffer or a strongly typed object (similar to spring controllers where we get body as an object `@RequestBody myobject`) or even as string.

**Comment by jkinkead** [comment]
This is likely because you're using HTTP2 (`h1Request` is only set if you're using HTTP/1.1). Can you fetch the body from the return value of [`getHttpRequest`](https://github.com/Nordstrom/xrpc/blob/master/src/main/java/com/nordstrom/xrpc/server/XrpcRequest.java#L85)?

**Comment by shine17** [comment]
context.getHttpRequest() is coming as null

**Comment by jkinkead** [comment]
Ah. That's because [this](https://github.com/Nordstrom/xrpc/blob/master/src/main/java/com/nordstrom/xrpc/server/XrpcRequest.java#L97) is returning the wrong variable - it should be the local `h1req`.

**Comment by shine17** [comment]
@jkinkead  it will be nice if we can have spring controller like feature for the request body with annotation `@RequestBody myobject ` , where we get the POJO for the body automatically with simple annotations.

**Comment by jkinkead** [comment]
I don't think we'll go annotations-based, since we're looking at a more functional system. There are other frameworks that do well with annotations-based stuff.
