### ISSUE TITLE
Need the ability to add additional netty pipelines and define the order of execution 

### ISSUE THREAD

**Issue by shine17** [Nordstrom/xrpc#33]
Currently in Router.java , we have our custom netty channel pipelines like rate limiter, connection limiter etc.
Users should get the ability to add additional pipelines like global exception handler , authorizer etc and should get the ability to specify the order of execution of pipelines.

**Comment by xjdr** [comment]
There is access to the pipeline via the XrpcRequest Object. If you need to have more configuration options prior to the codec in the pipeline, I think https://github.com/xjdr/xio is going to be a better fit for doing the dynamic pipeline composition.
