### ISSUE TITLE
Same path with different http verb causing runtime issues

### ISSUE THREAD

**Issue by shine17** [Nordstrom/xrpc#37]
eg :- 

router.addRoute("/people/{person}", personHandler, HttpMethod.GET);
router.addRoute("/people/{person}", someotherhandler, HttpMethod.PUT);

**Comment by xjdr** [comment]
Can you give more info on the issue?

**Comment by xjdr** [comment]
fixed by 1a9dc24c11f2082e543c604827b6ba9de755c273
