### ISSUE TITLE
Merge conflicts in xrpc client which is causing build issues

### ISSUE THREAD

**Issue by shine17** [Nordstrom/xrpc#40]
This file has merge conflicts in the xrpc master - 
https://github.com/Nordstrom/xrpc/blob/master/src/main/java/com/nordstrom/xrpc/client/XUrl.java

In the imports , we have merge conflicts which causes build errors

**Comment by xjdr** [comment]
Addressed by 0256e21a5168aab4493968d4792e897693da2fa7
