### ISSUE TITLE
Path Variables: final variable includes query string

### ISSUE THREAD

**Issue by forplayplay** [Nordstrom/xrpc#48]
for example, for the path:
`/people/{person}`

the following uri
`/people/patrick?exampleParam=something`

produces the following context:
`{person: "patrick?exampleParam=something"}`

we expect that it would be:
`{person: "patrick"}`

**Comment by jkinkead** [comment]
This looks like a duplicate of #27 . Are you using the latest xrpc?

**Comment by forplayplay** [comment]
It seemed as though #27 was fixed in 72a47e635f4c3469a0b9be810d1c891b17facf75 but it only fixed this issue for http1 requests.

**Comment by xjdr** [comment]
Addressed by 02fa63f918e4a34571a1541811a4e3ba23208f8f
